/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_scu_myndk_entity_Person */
#define TAG "MYTEST"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)
#ifndef NULL
#define NULL 0
#endif

#ifndef _Included_com_scu_myndk_entity_Person
#define _Included_com_scu_myndk_entity_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scu_myndk_entity_Person
 * Method:    average
 * Signature: ([Lcom/scu/myndk/entity/Person;)I
 */
JNIEXPORT jint JNICALL Java_com_scu_myndk_entity_Person_average
  (JNIEnv *, jobject, jobjectArray,jint);

/*
 * Class:     com_scu_myndk_entity_Person
 * Method:    average
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_scu_myndk_entity_Person_averages
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
