/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <android/log.h>
#include <string.h>
/* Header for class com_scu_myndk_entity_Native */

#ifndef _Included_com_scu_myndk_entity_Native
#define _Included_com_scu_myndk_entity_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef com_scu_myndk_entity_Native_TEST_BUFFER_SIZE
#define com_scu_myndk_entity_Native_TEST_BUFFER_SIZE 128L
/*
 * Class:     com_scu_myndk_entity_Native
 * Method:    nativeSetBuffer1
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_scu_myndk_entity_Native_nativeSetBuffer1
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_scu_myndk_entity_Native
 * Method:    nativeSetBuffer2
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_scu_myndk_entity_Native_nativeSetBuffer2
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
