/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#define TAG "myndk"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)
/* Header for class com_scu_myndk_MyNdk */

#ifndef _Included_com_scu_myndk_MyNdk
#define _Included_com_scu_myndk_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scu_myndk_MyNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scu_myndk_MyNdk_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_scu_myndk_MyNdk
 * Method:    getChangeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scu_myndk_MyNdk_getChangeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scu_myndk_MyNdk
 * Method:    changeBytes
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_scu_myndk_MyNdk_changeBytes
  (JNIEnv *, jobject, jbyteArray, jint);

JNIEXPORT void JNICALL Java_com_scu_myndk_MyNdk_toast
    (JNIEnv *,jobject,jobject);
#ifdef __cplusplus
}
#endif
#endif
